version: '3'
services:
  plunk:
    container_name: "plunk-service"
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: '${REDIS_URL}'
      DATABASE_URL: '${DATABASE_URL}'
      JWT_SECRET: '${JWT_SECRET}'
      AWS_REGION: '${AWS_REGION}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_SES_CONFIGURATION_SET: '${AWS_SES_CONFIGURATION_SET}'
      NEXT_PUBLIC_API_URI: '${API_URI}'
      API_URI: '${API_URI}'
      APP_URI: '${APP_URI}'
      DISABLE_SIGNUPS: '${DISABLE_SIGNUPS}'
    entrypoint: [ "/app/entry.sh" ]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    restart: always
